{% set setup_py = load_setup_py_data() %}
package:
    name: 'pyks'
    version: {{ setup_py.get('version') }}

source:
    path: ./

build:
    noarch: python
    number: 1
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    run:
        - python >=2.7
        - pandas >=0.20
        - numpy
    build:
        - python
        - setuptools

about:
    license: {{ setup_py.get('license') }}
    license_file: LICENSE
    summary: {{ setup_py.get('description') }}
